site_name: Awesome Java & Kotlin
site_description: Curated Java and Kotlin resourc
site_url: https://bsmahi.github.io/awesome-java-kotlin/
theme:
  name: material
  font:
     text: Roboto
     code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Java: java/index.md
  - Spring: spring/index.md
  - Testing: testing/index.md
  - Build Tools: build-tools/index.md
  - Cloud: cloud/index.md
  - AI: ai/index.md
  - Kotlin: kotlin/index.md
  - JVM: jvm/index.md